name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl: ^0.14.0
  location:  ^4.4.0
  web3dart: ^2.3.3
  fl_chart: ^0.60.0
  hex: ^0.2.0
  http: ^1.2.2
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

dependency_overrides:
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
